<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230420014446 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dtb_authority_role (id INT UNSIGNED AUTO_INCREMENT NOT NULL, authority_id SMALLINT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, deny_url VARCHAR(4000) NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_4A1F70B181EC865B (authority_id), INDEX IDX_4A1F70B161220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_base_info (id INT UNSIGNED AUTO_INCREMENT NOT NULL, country_id SMALLINT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, company_kana VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(8) DEFAULT NULL, addr01 VARCHAR(255) DEFAULT NULL, addr02 VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(14) DEFAULT NULL, business_hour VARCHAR(255) DEFAULT NULL, email01 VARCHAR(255) DEFAULT NULL, email02 VARCHAR(255) DEFAULT NULL, email03 VARCHAR(255) DEFAULT NULL, email04 VARCHAR(255) DEFAULT NULL, shop_name VARCHAR(255) DEFAULT NULL, shop_kana VARCHAR(255) DEFAULT NULL, shop_name_eng VARCHAR(255) DEFAULT NULL, update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', good_traded VARCHAR(4000) DEFAULT NULL, message VARCHAR(4000) DEFAULT NULL, delivery_free_amount NUMERIC(12, 2) UNSIGNED DEFAULT NULL, delivery_free_quantity INT UNSIGNED DEFAULT NULL, option_mypage_order_status_display TINYINT(1) DEFAULT 1 NOT NULL, option_nostock_hidden TINYINT(1) DEFAULT 0 NOT NULL, option_favorite_product TINYINT(1) DEFAULT 1 NOT NULL, option_product_delivery_fee TINYINT(1) DEFAULT 0 NOT NULL, invoice_registration_number VARCHAR(255) DEFAULT NULL, option_product_tax_rule TINYINT(1) DEFAULT 0 NOT NULL, option_customer_activate TINYINT(1) DEFAULT 1 NOT NULL, option_remember_me TINYINT(1) DEFAULT 1 NOT NULL, authentication_key VARCHAR(255) DEFAULT NULL, php_path VARCHAR(255) DEFAULT NULL, option_point TINYINT(1) DEFAULT 1 NOT NULL, basic_point_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'1\', point_conversion_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'1\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_1D3655F4F92F3E70 (country_id), INDEX IDX_1D3655F4E171EF5F (pref_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_block (id INT UNSIGNED AUTO_INCREMENT NOT NULL, device_type_id SMALLINT UNSIGNED DEFAULT NULL, block_name VARCHAR(255) DEFAULT NULL, file_name VARCHAR(255) NOT NULL, use_controller TINYINT(1) DEFAULT 0 NOT NULL, deletable TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_6B54DCBD4FFA550E (device_type_id), UNIQUE INDEX device_type_id (device_type_id, file_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_block_position (section INT UNSIGNED NOT NULL, block_id INT UNSIGNED NOT NULL, layout_id INT UNSIGNED NOT NULL, block_row INT UNSIGNED DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_35DCD731E9ED820C (block_id), INDEX IDX_35DCD7318C22AA1A (layout_id), PRIMARY KEY(section, block_id, layout_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_calendar (id INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, holiday DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_cart (id INT UNSIGNED AUTO_INCREMENT NOT NULL, customer_id INT UNSIGNED DEFAULT NULL, cart_key VARCHAR(255) DEFAULT NULL, pre_order_id VARCHAR(255) DEFAULT NULL, total_price NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, delivery_fee_total NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, sort_no SMALLINT UNSIGNED DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', add_point NUMERIC(12, 0) UNSIGNED DEFAULT \'0\' NOT NULL, use_point NUMERIC(12, 0) UNSIGNED DEFAULT \'0\' NOT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_FC3C24F09395C3F3 (customer_id), INDEX dtb_cart_update_date_idx (update_date), UNIQUE INDEX dtb_cart_pre_order_id_idx (pre_order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_cart_item (id INT UNSIGNED AUTO_INCREMENT NOT NULL, product_class_id INT UNSIGNED DEFAULT NULL, cart_id INT UNSIGNED DEFAULT NULL, price NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, quantity NUMERIC(10, 0) DEFAULT \'0\' NOT NULL, point_rate NUMERIC(10, 0) UNSIGNED DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_B0228F7421B06187 (product_class_id), INDEX IDX_B0228F741AD5CDBF (cart_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_category (id INT UNSIGNED AUTO_INCREMENT NOT NULL, parent_category_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, category_name VARCHAR(255) NOT NULL, hierarchy INT UNSIGNED NOT NULL, sort_no INT NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_5ED2C2B796A8F92 (parent_category_id), INDEX IDX_5ED2C2B61220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_class_category (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_name_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, backend_name VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, sort_no INT UNSIGNED NOT NULL, visible TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_9B0D1DBAB462FB2A (class_name_id), INDEX IDX_9B0D1DBA61220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_class_name (id INT UNSIGNED AUTO_INCREMENT NOT NULL, creator_id INT UNSIGNED DEFAULT NULL, backend_name VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, sort_no INT UNSIGNED NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_187C95AD61220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_csv (id INT UNSIGNED AUTO_INCREMENT NOT NULL, csv_type_id SMALLINT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, entity_name VARCHAR(255) NOT NULL, field_name VARCHAR(255) NOT NULL, reference_field_name VARCHAR(255) DEFAULT NULL, disp_name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_F55F48C3E8507796 (csv_type_id), INDEX IDX_F55F48C361220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_customer (id INT UNSIGNED AUTO_INCREMENT NOT NULL, customer_status_id SMALLINT UNSIGNED DEFAULT NULL, sex_id SMALLINT UNSIGNED DEFAULT NULL, job_id SMALLINT UNSIGNED DEFAULT NULL, country_id SMALLINT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, name01 VARCHAR(255) NOT NULL, name02 VARCHAR(255) NOT NULL, kana01 VARCHAR(255) DEFAULT NULL, kana02 VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(8) DEFAULT NULL, addr01 VARCHAR(255) DEFAULT NULL, addr02 VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, phone_number VARCHAR(14) DEFAULT NULL, birth DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', password VARCHAR(255) NOT NULL, salt VARCHAR(255) DEFAULT NULL, secret_key VARCHAR(255) NOT NULL, first_buy_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', last_buy_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', buy_times NUMERIC(10, 0) UNSIGNED DEFAULT \'0\', buy_total NUMERIC(12, 2) UNSIGNED DEFAULT \'0\', note VARCHAR(4000) DEFAULT NULL, reset_key VARCHAR(255) DEFAULT NULL, reset_expire DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', point NUMERIC(12, 0) DEFAULT \'0\' NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_8298BBE3C00AF8A7 (customer_status_id), INDEX IDX_8298BBE35A2DB2A0 (sex_id), INDEX IDX_8298BBE3BE04EA9 (job_id), INDEX IDX_8298BBE3F92F3E70 (country_id), INDEX IDX_8298BBE3E171EF5F (pref_id), INDEX dtb_customer_buy_times_idx (buy_times), INDEX dtb_customer_buy_total_idx (buy_total), INDEX dtb_customer_create_date_idx (create_date), INDEX dtb_customer_update_date_idx (update_date), INDEX dtb_customer_last_buy_date_idx (last_buy_date), INDEX dtb_customer_email_idx (email), UNIQUE INDEX secret_key (secret_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_customer_address (id INT UNSIGNED AUTO_INCREMENT NOT NULL, customer_id INT UNSIGNED DEFAULT NULL, country_id SMALLINT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, name01 VARCHAR(255) NOT NULL, name02 VARCHAR(255) NOT NULL, kana01 VARCHAR(255) DEFAULT NULL, kana02 VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(8) DEFAULT NULL, addr01 VARCHAR(255) DEFAULT NULL, addr02 VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(14) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_6C38C0F89395C3F3 (customer_id), INDEX IDX_6C38C0F8F92F3E70 (country_id), INDEX IDX_6C38C0F8E171EF5F (pref_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_customer_favorite_product (id INT UNSIGNED AUTO_INCREMENT NOT NULL, customer_id INT UNSIGNED DEFAULT NULL, product_id INT UNSIGNED DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_ED6313839395C3F3 (customer_id), INDEX IDX_ED6313834584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_delivery (id INT UNSIGNED AUTO_INCREMENT NOT NULL, creator_id INT UNSIGNED DEFAULT NULL, sale_type_id SMALLINT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, service_name VARCHAR(255) DEFAULT NULL, description VARCHAR(4000) DEFAULT NULL, confirm_url VARCHAR(4000) DEFAULT NULL, sort_no INT UNSIGNED DEFAULT NULL, visible TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_3420D9FA61220EA6 (creator_id), INDEX IDX_3420D9FAB0524E01 (sale_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_delivery_duration (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, duration SMALLINT DEFAULT 0 NOT NULL, sort_no INT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_delivery_fee (id INT UNSIGNED AUTO_INCREMENT NOT NULL, delivery_id INT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, fee NUMERIC(12, 2) UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_491552412136921 (delivery_id), INDEX IDX_4915524E171EF5F (pref_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_delivery_time (id INT UNSIGNED AUTO_INCREMENT NOT NULL, delivery_id INT UNSIGNED DEFAULT NULL, delivery_time VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, visible TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_E80EE3A612136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_layout (id INT UNSIGNED AUTO_INCREMENT NOT NULL, device_type_id SMALLINT UNSIGNED DEFAULT NULL, layout_name VARCHAR(255) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_5A62AA7C4FFA550E (device_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_login_history (id INT UNSIGNED AUTO_INCREMENT NOT NULL, login_history_status_id SMALLINT UNSIGNED NOT NULL, member_id INT UNSIGNED DEFAULT NULL, user_name LONGTEXT DEFAULT NULL, client_ip LONGTEXT DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_6191DD4F9FA62FDD (login_history_status_id), INDEX IDX_6191DD4F7597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_mail_history (id INT UNSIGNED AUTO_INCREMENT NOT NULL, order_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, send_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', mail_subject VARCHAR(255) DEFAULT NULL, mail_body LONGTEXT DEFAULT NULL, mail_html_body LONGTEXT DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_4870AB118D9F6D38 (order_id), INDEX IDX_4870AB1161220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_mail_template (id INT UNSIGNED AUTO_INCREMENT NOT NULL, creator_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, file_name VARCHAR(255) DEFAULT NULL, mail_subject VARCHAR(255) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_1CB16DB261220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_member (id INT UNSIGNED AUTO_INCREMENT NOT NULL, work_id SMALLINT UNSIGNED DEFAULT NULL, authority_id SMALLINT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, department VARCHAR(255) DEFAULT NULL, login_id VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) DEFAULT NULL, sort_no SMALLINT UNSIGNED NOT NULL, two_factor_auth_key VARCHAR(255) DEFAULT NULL, two_factor_auth_enabled TINYINT(1) DEFAULT 0 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', login_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_10BC3BE6BB3453DB (work_id), INDEX IDX_10BC3BE681EC865B (authority_id), INDEX IDX_10BC3BE661220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_news (id INT UNSIGNED AUTO_INCREMENT NOT NULL, creator_id INT UNSIGNED DEFAULT NULL, publish_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, url VARCHAR(4000) DEFAULT NULL, link_method TINYINT(1) DEFAULT 0 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', visible TINYINT(1) DEFAULT 1 NOT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_EA4C351761220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_order (id INT UNSIGNED AUTO_INCREMENT NOT NULL, customer_id INT UNSIGNED DEFAULT NULL, country_id SMALLINT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, sex_id SMALLINT UNSIGNED DEFAULT NULL, job_id SMALLINT UNSIGNED DEFAULT NULL, payment_id INT UNSIGNED DEFAULT NULL, device_type_id SMALLINT UNSIGNED DEFAULT NULL, pre_order_id VARCHAR(255) DEFAULT NULL, order_no VARCHAR(255) DEFAULT NULL, message VARCHAR(4000) DEFAULT NULL, name01 VARCHAR(255) NOT NULL, name02 VARCHAR(255) NOT NULL, kana01 VARCHAR(255) DEFAULT NULL, kana02 VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(14) DEFAULT NULL, postal_code VARCHAR(8) DEFAULT NULL, addr01 VARCHAR(255) DEFAULT NULL, addr02 VARCHAR(255) DEFAULT NULL, birth DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', subtotal NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, discount NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, delivery_fee_total NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, charge NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, tax NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, total NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, payment_total NUMERIC(12, 2) UNSIGNED DEFAULT \'0\' NOT NULL, payment_method VARCHAR(255) DEFAULT NULL, note VARCHAR(4000) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', order_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', payment_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', currency_code VARCHAR(255) DEFAULT NULL, complete_message LONGTEXT DEFAULT NULL, complete_mail_message LONGTEXT DEFAULT NULL, add_point NUMERIC(12, 0) UNSIGNED DEFAULT \'0\' NOT NULL, use_point NUMERIC(12, 0) UNSIGNED DEFAULT \'0\' NOT NULL, order_status_id SMALLINT UNSIGNED DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_1D66D8079395C3F3 (customer_id), INDEX IDX_1D66D807F92F3E70 (country_id), INDEX IDX_1D66D807E171EF5F (pref_id), INDEX IDX_1D66D8075A2DB2A0 (sex_id), INDEX IDX_1D66D807BE04EA9 (job_id), INDEX IDX_1D66D8074C3A3BB (payment_id), INDEX IDX_1D66D8074FFA550E (device_type_id), INDEX IDX_1D66D807D7707B45 (order_status_id), INDEX dtb_order_email_idx (email), INDEX dtb_order_order_date_idx (order_date), INDEX dtb_order_payment_date_idx (payment_date), INDEX dtb_order_update_date_idx (update_date), INDEX dtb_order_order_no_idx (order_no), UNIQUE INDEX dtb_order_pre_order_id_idx (pre_order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_order_item (id INT UNSIGNED AUTO_INCREMENT NOT NULL, order_id INT UNSIGNED DEFAULT NULL, product_id INT UNSIGNED DEFAULT NULL, product_class_id INT UNSIGNED DEFAULT NULL, shipping_id INT UNSIGNED DEFAULT NULL, rounding_type_id SMALLINT UNSIGNED DEFAULT NULL, tax_type_id SMALLINT UNSIGNED DEFAULT NULL, tax_display_type_id SMALLINT UNSIGNED DEFAULT NULL, order_item_type_id SMALLINT UNSIGNED DEFAULT NULL, product_name VARCHAR(255) NOT NULL, product_code VARCHAR(255) DEFAULT NULL, class_name1 VARCHAR(255) DEFAULT NULL, class_name2 VARCHAR(255) DEFAULT NULL, class_category_name1 VARCHAR(255) DEFAULT NULL, class_category_name2 VARCHAR(255) DEFAULT NULL, price NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, quantity NUMERIC(10, 0) DEFAULT \'0\' NOT NULL, tax NUMERIC(10, 0) DEFAULT \'0\' NOT NULL, tax_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'0\' NOT NULL, tax_adjust NUMERIC(10, 0) UNSIGNED DEFAULT \'0\' NOT NULL, tax_rule_id SMALLINT UNSIGNED DEFAULT NULL, currency_code VARCHAR(255) DEFAULT NULL, processor_name VARCHAR(255) DEFAULT NULL, point_rate NUMERIC(10, 0) UNSIGNED DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_A0C8C3ED8D9F6D38 (order_id), INDEX IDX_A0C8C3ED4584665A (product_id), INDEX IDX_A0C8C3ED21B06187 (product_class_id), INDEX IDX_A0C8C3ED4887F3F8 (shipping_id), INDEX IDX_A0C8C3ED1BD5C574 (rounding_type_id), INDEX IDX_A0C8C3ED84042C99 (tax_type_id), INDEX IDX_A0C8C3EDA2505856 (tax_display_type_id), INDEX IDX_A0C8C3EDCAD13EAD (order_item_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_order_pdf (member_id INT UNSIGNED NOT NULL, title VARCHAR(255) DEFAULT NULL, message1 VARCHAR(255) DEFAULT NULL, message2 VARCHAR(255) DEFAULT NULL, message3 VARCHAR(255) DEFAULT NULL, note1 VARCHAR(255) DEFAULT NULL, note2 VARCHAR(255) DEFAULT NULL, note3 VARCHAR(255) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', visible TINYINT(1) DEFAULT 1 NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(member_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_page (id INT UNSIGNED AUTO_INCREMENT NOT NULL, master_page_id INT UNSIGNED DEFAULT NULL, page_name VARCHAR(255) DEFAULT NULL, url VARCHAR(255) NOT NULL, file_name VARCHAR(255) DEFAULT NULL, edit_type SMALLINT UNSIGNED DEFAULT 1 NOT NULL, author VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, keyword VARCHAR(255) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', meta_robots VARCHAR(255) DEFAULT NULL, meta_tags VARCHAR(4000) DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_E3951A67D0618E8C (master_page_id), INDEX dtb_page_url_idx (url), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_page_layout (page_id INT UNSIGNED NOT NULL, layout_id INT UNSIGNED NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_F2799941C4663E4 (page_id), INDEX IDX_F27999418C22AA1A (layout_id), PRIMARY KEY(page_id, layout_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_payment (id INT UNSIGNED AUTO_INCREMENT NOT NULL, creator_id INT UNSIGNED DEFAULT NULL, payment_method VARCHAR(255) DEFAULT NULL, charge NUMERIC(12, 2) UNSIGNED DEFAULT \'0\', rule_max NUMERIC(12, 2) UNSIGNED DEFAULT NULL, sort_no SMALLINT UNSIGNED DEFAULT NULL, fixed TINYINT(1) DEFAULT 1 NOT NULL, payment_image VARCHAR(255) DEFAULT NULL, rule_min NUMERIC(12, 2) UNSIGNED DEFAULT NULL, method_class VARCHAR(255) DEFAULT NULL, visible TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_7AFF628F61220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_payment_option (delivery_id INT UNSIGNED NOT NULL, payment_id INT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_5631540D12136921 (delivery_id), INDEX IDX_5631540D4C3A3BB (payment_id), PRIMARY KEY(delivery_id, payment_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_plugin (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, enabled TINYINT(1) DEFAULT 0 NOT NULL, version VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, initialized TINYINT(1) DEFAULT 0 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_product (id INT UNSIGNED AUTO_INCREMENT NOT NULL, creator_id INT UNSIGNED DEFAULT NULL, product_status_id SMALLINT UNSIGNED DEFAULT NULL, name VARCHAR(255) NOT NULL, note LONGTEXT DEFAULT NULL, description_list LONGTEXT DEFAULT NULL, description_detail LONGTEXT DEFAULT NULL, search_word LONGTEXT DEFAULT NULL, free_area LONGTEXT DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_C49DE22F61220EA6 (creator_id), INDEX IDX_C49DE22F557B630 (product_status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_product_category (product_id INT UNSIGNED NOT NULL, category_id INT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_B05778914584665A (product_id), INDEX IDX_B057789112469DE2 (category_id), PRIMARY KEY(product_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_product_class (id INT UNSIGNED AUTO_INCREMENT NOT NULL, product_id INT UNSIGNED DEFAULT NULL, sale_type_id SMALLINT UNSIGNED DEFAULT NULL, class_category_id1 INT UNSIGNED DEFAULT NULL, class_category_id2 INT UNSIGNED DEFAULT NULL, delivery_duration_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, product_code VARCHAR(255) DEFAULT NULL, stock NUMERIC(10, 0) DEFAULT NULL, stock_unlimited TINYINT(1) DEFAULT 0 NOT NULL, sale_limit NUMERIC(10, 0) UNSIGNED DEFAULT NULL, price01 NUMERIC(12, 2) DEFAULT NULL, price02 NUMERIC(12, 2) NOT NULL, delivery_fee NUMERIC(12, 2) UNSIGNED DEFAULT NULL, visible TINYINT(1) DEFAULT 1 NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', currency_code VARCHAR(255) DEFAULT NULL, point_rate NUMERIC(10, 0) UNSIGNED DEFAULT NULL, discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_1A11D1BA4584665A (product_id), INDEX IDX_1A11D1BAB0524E01 (sale_type_id), INDEX IDX_1A11D1BA248D128 (class_category_id1), INDEX IDX_1A11D1BA9B418092 (class_category_id2), INDEX IDX_1A11D1BABA4269E (delivery_duration_id), INDEX IDX_1A11D1BA61220EA6 (creator_id), INDEX dtb_product_class_price02_idx (price02), INDEX dtb_product_class_stock_stock_unlimited_idx (stock, stock_unlimited), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_product_image (id INT UNSIGNED AUTO_INCREMENT NOT NULL, product_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, file_name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_3267CC7A4584665A (product_id), INDEX IDX_3267CC7A61220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_product_stock (id INT UNSIGNED AUTO_INCREMENT NOT NULL, product_class_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, stock NUMERIC(10, 0) DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_BC6C9E4521B06187 (product_class_id), INDEX IDX_BC6C9E4561220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_product_tag (id INT UNSIGNED AUTO_INCREMENT NOT NULL, product_id INT UNSIGNED DEFAULT NULL, tag_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_4433E7214584665A (product_id), INDEX IDX_4433E721BAD26311 (tag_id), INDEX IDX_4433E72161220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_shipping (id INT UNSIGNED AUTO_INCREMENT NOT NULL, order_id INT UNSIGNED DEFAULT NULL, country_id SMALLINT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, delivery_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, name01 VARCHAR(255) NOT NULL, name02 VARCHAR(255) NOT NULL, kana01 VARCHAR(255) DEFAULT NULL, kana02 VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(14) DEFAULT NULL, postal_code VARCHAR(8) DEFAULT NULL, addr01 VARCHAR(255) DEFAULT NULL, addr02 VARCHAR(255) DEFAULT NULL, delivery_name VARCHAR(255) DEFAULT NULL, time_id INT UNSIGNED DEFAULT NULL, delivery_time VARCHAR(255) DEFAULT NULL, delivery_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', shipping_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', tracking_number VARCHAR(255) DEFAULT NULL, note VARCHAR(4000) DEFAULT NULL, sort_no SMALLINT UNSIGNED DEFAULT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', mail_send_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_2EBD22CE8D9F6D38 (order_id), INDEX IDX_2EBD22CEF92F3E70 (country_id), INDEX IDX_2EBD22CEE171EF5F (pref_id), INDEX IDX_2EBD22CE12136921 (delivery_id), INDEX IDX_2EBD22CE61220EA6 (creator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_tag (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_tax_rule (id INT UNSIGNED AUTO_INCREMENT NOT NULL, product_class_id INT UNSIGNED DEFAULT NULL, creator_id INT UNSIGNED DEFAULT NULL, country_id SMALLINT UNSIGNED DEFAULT NULL, pref_id SMALLINT UNSIGNED DEFAULT NULL, product_id INT UNSIGNED DEFAULT NULL, rounding_type_id SMALLINT UNSIGNED DEFAULT NULL, tax_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'0\' NOT NULL, tax_adjust NUMERIC(10, 0) UNSIGNED DEFAULT \'0\' NOT NULL, apply_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_59F696DE21B06187 (product_class_id), INDEX IDX_59F696DE61220EA6 (creator_id), INDEX IDX_59F696DEF92F3E70 (country_id), INDEX IDX_59F696DEE171EF5F (pref_id), INDEX IDX_59F696DE4584665A (product_id), INDEX IDX_59F696DE1BD5C574 (rounding_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_template (id INT UNSIGNED AUTO_INCREMENT NOT NULL, device_type_id SMALLINT UNSIGNED DEFAULT NULL, template_code VARCHAR(255) NOT NULL, template_name VARCHAR(255) NOT NULL, create_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', update_date DATETIME NOT NULL COMMENT \'(DC2Type:datetimetz)\', discriminator_type VARCHAR(255) NOT NULL, INDEX IDX_94C12A694FFA550E (device_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dtb_tradelaw (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(4000) DEFAULT NULL, sort_no SMALLINT NOT NULL, display_order_screen TINYINT(1) NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_authority (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_country (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_csv_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_customer_order_status (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_customer_status (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_device_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_job (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_login_history_status (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_order_item_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_order_status (id SMALLINT UNSIGNED NOT NULL, display_order_count TINYINT(1) DEFAULT 0 NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_order_status_color (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_page_max (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_pref (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_product_list_max (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_product_list_order_by (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_product_status (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_rounding_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_sale_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_sex (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_tax_display_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_tax_type (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mtb_work (id SMALLINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, sort_no SMALLINT UNSIGNED NOT NULL, discriminator_type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE dtb_authority_role ADD CONSTRAINT FK_4A1F70B181EC865B FOREIGN KEY (authority_id) REFERENCES mtb_authority (id)');
        $this->addSql('ALTER TABLE dtb_authority_role ADD CONSTRAINT FK_4A1F70B161220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_base_info ADD CONSTRAINT FK_1D3655F4F92F3E70 FOREIGN KEY (country_id) REFERENCES mtb_country (id)');
        $this->addSql('ALTER TABLE dtb_base_info ADD CONSTRAINT FK_1D3655F4E171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_block ADD CONSTRAINT FK_6B54DCBD4FFA550E FOREIGN KEY (device_type_id) REFERENCES mtb_device_type (id)');
        $this->addSql('ALTER TABLE dtb_block_position ADD CONSTRAINT FK_35DCD731E9ED820C FOREIGN KEY (block_id) REFERENCES dtb_block (id)');
        $this->addSql('ALTER TABLE dtb_block_position ADD CONSTRAINT FK_35DCD7318C22AA1A FOREIGN KEY (layout_id) REFERENCES dtb_layout (id)');
        $this->addSql('ALTER TABLE dtb_cart ADD CONSTRAINT FK_FC3C24F09395C3F3 FOREIGN KEY (customer_id) REFERENCES dtb_customer (id)');
        $this->addSql('ALTER TABLE dtb_cart_item ADD CONSTRAINT FK_B0228F7421B06187 FOREIGN KEY (product_class_id) REFERENCES dtb_product_class (id)');
        $this->addSql('ALTER TABLE dtb_cart_item ADD CONSTRAINT FK_B0228F741AD5CDBF FOREIGN KEY (cart_id) REFERENCES dtb_cart (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dtb_category ADD CONSTRAINT FK_5ED2C2B796A8F92 FOREIGN KEY (parent_category_id) REFERENCES dtb_category (id)');
        $this->addSql('ALTER TABLE dtb_category ADD CONSTRAINT FK_5ED2C2B61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_class_category ADD CONSTRAINT FK_9B0D1DBAB462FB2A FOREIGN KEY (class_name_id) REFERENCES dtb_class_name (id)');
        $this->addSql('ALTER TABLE dtb_class_category ADD CONSTRAINT FK_9B0D1DBA61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_class_name ADD CONSTRAINT FK_187C95AD61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_csv ADD CONSTRAINT FK_F55F48C3E8507796 FOREIGN KEY (csv_type_id) REFERENCES mtb_csv_type (id)');
        $this->addSql('ALTER TABLE dtb_csv ADD CONSTRAINT FK_F55F48C361220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_customer ADD CONSTRAINT FK_8298BBE3C00AF8A7 FOREIGN KEY (customer_status_id) REFERENCES mtb_customer_status (id)');
        $this->addSql('ALTER TABLE dtb_customer ADD CONSTRAINT FK_8298BBE35A2DB2A0 FOREIGN KEY (sex_id) REFERENCES mtb_sex (id)');
        $this->addSql('ALTER TABLE dtb_customer ADD CONSTRAINT FK_8298BBE3BE04EA9 FOREIGN KEY (job_id) REFERENCES mtb_job (id)');
        $this->addSql('ALTER TABLE dtb_customer ADD CONSTRAINT FK_8298BBE3F92F3E70 FOREIGN KEY (country_id) REFERENCES mtb_country (id)');
        $this->addSql('ALTER TABLE dtb_customer ADD CONSTRAINT FK_8298BBE3E171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_customer_address ADD CONSTRAINT FK_6C38C0F89395C3F3 FOREIGN KEY (customer_id) REFERENCES dtb_customer (id)');
        $this->addSql('ALTER TABLE dtb_customer_address ADD CONSTRAINT FK_6C38C0F8F92F3E70 FOREIGN KEY (country_id) REFERENCES mtb_country (id)');
        $this->addSql('ALTER TABLE dtb_customer_address ADD CONSTRAINT FK_6C38C0F8E171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_customer_favorite_product ADD CONSTRAINT FK_ED6313839395C3F3 FOREIGN KEY (customer_id) REFERENCES dtb_customer (id)');
        $this->addSql('ALTER TABLE dtb_customer_favorite_product ADD CONSTRAINT FK_ED6313834584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_delivery ADD CONSTRAINT FK_3420D9FA61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_delivery ADD CONSTRAINT FK_3420D9FAB0524E01 FOREIGN KEY (sale_type_id) REFERENCES mtb_sale_type (id)');
        $this->addSql('ALTER TABLE dtb_delivery_fee ADD CONSTRAINT FK_491552412136921 FOREIGN KEY (delivery_id) REFERENCES dtb_delivery (id)');
        $this->addSql('ALTER TABLE dtb_delivery_fee ADD CONSTRAINT FK_4915524E171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_delivery_time ADD CONSTRAINT FK_E80EE3A612136921 FOREIGN KEY (delivery_id) REFERENCES dtb_delivery (id)');
        $this->addSql('ALTER TABLE dtb_layout ADD CONSTRAINT FK_5A62AA7C4FFA550E FOREIGN KEY (device_type_id) REFERENCES mtb_device_type (id)');
        $this->addSql('ALTER TABLE dtb_login_history ADD CONSTRAINT FK_6191DD4F9FA62FDD FOREIGN KEY (login_history_status_id) REFERENCES mtb_login_history_status (id)');
        $this->addSql('ALTER TABLE dtb_login_history ADD CONSTRAINT FK_6191DD4F7597D3FE FOREIGN KEY (member_id) REFERENCES dtb_member (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE dtb_mail_history ADD CONSTRAINT FK_4870AB118D9F6D38 FOREIGN KEY (order_id) REFERENCES dtb_order (id)');
        $this->addSql('ALTER TABLE dtb_mail_history ADD CONSTRAINT FK_4870AB1161220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_mail_template ADD CONSTRAINT FK_1CB16DB261220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_member ADD CONSTRAINT FK_10BC3BE6BB3453DB FOREIGN KEY (work_id) REFERENCES mtb_work (id)');
        $this->addSql('ALTER TABLE dtb_member ADD CONSTRAINT FK_10BC3BE681EC865B FOREIGN KEY (authority_id) REFERENCES mtb_authority (id)');
        $this->addSql('ALTER TABLE dtb_member ADD CONSTRAINT FK_10BC3BE661220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_news ADD CONSTRAINT FK_EA4C351761220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D8079395C3F3 FOREIGN KEY (customer_id) REFERENCES dtb_customer (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D807F92F3E70 FOREIGN KEY (country_id) REFERENCES mtb_country (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D807E171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D8075A2DB2A0 FOREIGN KEY (sex_id) REFERENCES mtb_sex (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D807BE04EA9 FOREIGN KEY (job_id) REFERENCES mtb_job (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D8074C3A3BB FOREIGN KEY (payment_id) REFERENCES dtb_payment (id)');
        $this->addSql('ALTER TABLE dtb_order ADD CONSTRAINT FK_1D66D8074FFA550E FOREIGN KEY (device_type_id) REFERENCES mtb_device_type (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3ED8D9F6D38 FOREIGN KEY (order_id) REFERENCES dtb_order (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3ED4584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3ED21B06187 FOREIGN KEY (product_class_id) REFERENCES dtb_product_class (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3ED4887F3F8 FOREIGN KEY (shipping_id) REFERENCES dtb_shipping (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3ED1BD5C574 FOREIGN KEY (rounding_type_id) REFERENCES mtb_rounding_type (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3ED84042C99 FOREIGN KEY (tax_type_id) REFERENCES mtb_tax_type (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3EDA2505856 FOREIGN KEY (tax_display_type_id) REFERENCES mtb_tax_display_type (id)');
        $this->addSql('ALTER TABLE dtb_order_item ADD CONSTRAINT FK_A0C8C3EDCAD13EAD FOREIGN KEY (order_item_type_id) REFERENCES mtb_order_item_type (id)');
        $this->addSql('ALTER TABLE dtb_page ADD CONSTRAINT FK_E3951A67D0618E8C FOREIGN KEY (master_page_id) REFERENCES dtb_page (id)');
        $this->addSql('ALTER TABLE dtb_page_layout ADD CONSTRAINT FK_F2799941C4663E4 FOREIGN KEY (page_id) REFERENCES dtb_page (id)');
        $this->addSql('ALTER TABLE dtb_page_layout ADD CONSTRAINT FK_F27999418C22AA1A FOREIGN KEY (layout_id) REFERENCES dtb_layout (id)');
        $this->addSql('ALTER TABLE dtb_payment ADD CONSTRAINT FK_7AFF628F61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_payment_option ADD CONSTRAINT FK_5631540D12136921 FOREIGN KEY (delivery_id) REFERENCES dtb_delivery (id)');
        $this->addSql('ALTER TABLE dtb_payment_option ADD CONSTRAINT FK_5631540D4C3A3BB FOREIGN KEY (payment_id) REFERENCES dtb_payment (id)');
        $this->addSql('ALTER TABLE dtb_product ADD CONSTRAINT FK_C49DE22F61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_product ADD CONSTRAINT FK_C49DE22F557B630 FOREIGN KEY (product_status_id) REFERENCES mtb_product_status (id)');
        $this->addSql('ALTER TABLE dtb_product_category ADD CONSTRAINT FK_B05778914584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_product_category ADD CONSTRAINT FK_B057789112469DE2 FOREIGN KEY (category_id) REFERENCES dtb_category (id)');
        $this->addSql('ALTER TABLE dtb_product_class ADD CONSTRAINT FK_1A11D1BA4584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_product_class ADD CONSTRAINT FK_1A11D1BAB0524E01 FOREIGN KEY (sale_type_id) REFERENCES mtb_sale_type (id)');
        $this->addSql('ALTER TABLE dtb_product_class ADD CONSTRAINT FK_1A11D1BA248D128 FOREIGN KEY (class_category_id1) REFERENCES dtb_class_category (id)');
        $this->addSql('ALTER TABLE dtb_product_class ADD CONSTRAINT FK_1A11D1BA9B418092 FOREIGN KEY (class_category_id2) REFERENCES dtb_class_category (id)');
        $this->addSql('ALTER TABLE dtb_product_class ADD CONSTRAINT FK_1A11D1BABA4269E FOREIGN KEY (delivery_duration_id) REFERENCES dtb_delivery_duration (id)');
        $this->addSql('ALTER TABLE dtb_product_class ADD CONSTRAINT FK_1A11D1BA61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_product_image ADD CONSTRAINT FK_3267CC7A4584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_product_image ADD CONSTRAINT FK_3267CC7A61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_product_stock ADD CONSTRAINT FK_BC6C9E4521B06187 FOREIGN KEY (product_class_id) REFERENCES dtb_product_class (id)');
        $this->addSql('ALTER TABLE dtb_product_stock ADD CONSTRAINT FK_BC6C9E4561220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_product_tag ADD CONSTRAINT FK_4433E7214584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_product_tag ADD CONSTRAINT FK_4433E721BAD26311 FOREIGN KEY (tag_id) REFERENCES dtb_tag (id)');
        $this->addSql('ALTER TABLE dtb_product_tag ADD CONSTRAINT FK_4433E72161220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_shipping ADD CONSTRAINT FK_2EBD22CE8D9F6D38 FOREIGN KEY (order_id) REFERENCES dtb_order (id)');
        $this->addSql('ALTER TABLE dtb_shipping ADD CONSTRAINT FK_2EBD22CEF92F3E70 FOREIGN KEY (country_id) REFERENCES mtb_country (id)');
        $this->addSql('ALTER TABLE dtb_shipping ADD CONSTRAINT FK_2EBD22CEE171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_shipping ADD CONSTRAINT FK_2EBD22CE12136921 FOREIGN KEY (delivery_id) REFERENCES dtb_delivery (id)');
        $this->addSql('ALTER TABLE dtb_shipping ADD CONSTRAINT FK_2EBD22CE61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_tax_rule ADD CONSTRAINT FK_59F696DE21B06187 FOREIGN KEY (product_class_id) REFERENCES dtb_product_class (id)');
        $this->addSql('ALTER TABLE dtb_tax_rule ADD CONSTRAINT FK_59F696DE61220EA6 FOREIGN KEY (creator_id) REFERENCES dtb_member (id)');
        $this->addSql('ALTER TABLE dtb_tax_rule ADD CONSTRAINT FK_59F696DEF92F3E70 FOREIGN KEY (country_id) REFERENCES mtb_country (id)');
        $this->addSql('ALTER TABLE dtb_tax_rule ADD CONSTRAINT FK_59F696DEE171EF5F FOREIGN KEY (pref_id) REFERENCES mtb_pref (id)');
        $this->addSql('ALTER TABLE dtb_tax_rule ADD CONSTRAINT FK_59F696DE4584665A FOREIGN KEY (product_id) REFERENCES dtb_product (id)');
        $this->addSql('ALTER TABLE dtb_tax_rule ADD CONSTRAINT FK_59F696DE1BD5C574 FOREIGN KEY (rounding_type_id) REFERENCES mtb_rounding_type (id)');
        $this->addSql('ALTER TABLE dtb_template ADD CONSTRAINT FK_94C12A694FFA550E FOREIGN KEY (device_type_id) REFERENCES mtb_device_type (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        // $this->addSql('ALTER TABLE dtb_authority_role DROP FOREIGN KEY FK_4A1F70B181EC865B');
        // $this->addSql('ALTER TABLE dtb_authority_role DROP FOREIGN KEY FK_4A1F70B161220EA6');
        // $this->addSql('ALTER TABLE dtb_base_info DROP FOREIGN KEY FK_1D3655F4F92F3E70');
        // $this->addSql('ALTER TABLE dtb_base_info DROP FOREIGN KEY FK_1D3655F4E171EF5F');
        // $this->addSql('ALTER TABLE dtb_block DROP FOREIGN KEY FK_6B54DCBD4FFA550E');
        // $this->addSql('ALTER TABLE dtb_block_position DROP FOREIGN KEY FK_35DCD731E9ED820C');
        // $this->addSql('ALTER TABLE dtb_block_position DROP FOREIGN KEY FK_35DCD7318C22AA1A');
        // $this->addSql('ALTER TABLE dtb_cart DROP FOREIGN KEY FK_FC3C24F09395C3F3');
        // $this->addSql('ALTER TABLE dtb_cart_item DROP FOREIGN KEY FK_B0228F7421B06187');
        // $this->addSql('ALTER TABLE dtb_cart_item DROP FOREIGN KEY FK_B0228F741AD5CDBF');
        // $this->addSql('ALTER TABLE dtb_category DROP FOREIGN KEY FK_5ED2C2B796A8F92');
        // $this->addSql('ALTER TABLE dtb_category DROP FOREIGN KEY FK_5ED2C2B61220EA6');
        // $this->addSql('ALTER TABLE dtb_class_category DROP FOREIGN KEY FK_9B0D1DBAB462FB2A');
        // $this->addSql('ALTER TABLE dtb_class_category DROP FOREIGN KEY FK_9B0D1DBA61220EA6');
        // $this->addSql('ALTER TABLE dtb_class_name DROP FOREIGN KEY FK_187C95AD61220EA6');
        // $this->addSql('ALTER TABLE dtb_csv DROP FOREIGN KEY FK_F55F48C3E8507796');
        // $this->addSql('ALTER TABLE dtb_csv DROP FOREIGN KEY FK_F55F48C361220EA6');
        // $this->addSql('ALTER TABLE dtb_customer DROP FOREIGN KEY FK_8298BBE3C00AF8A7');
        // $this->addSql('ALTER TABLE dtb_customer DROP FOREIGN KEY FK_8298BBE35A2DB2A0');
        // $this->addSql('ALTER TABLE dtb_customer DROP FOREIGN KEY FK_8298BBE3BE04EA9');
        // $this->addSql('ALTER TABLE dtb_customer DROP FOREIGN KEY FK_8298BBE3F92F3E70');
        // $this->addSql('ALTER TABLE dtb_customer DROP FOREIGN KEY FK_8298BBE3E171EF5F');
        // $this->addSql('ALTER TABLE dtb_customer_address DROP FOREIGN KEY FK_6C38C0F89395C3F3');
        // $this->addSql('ALTER TABLE dtb_customer_address DROP FOREIGN KEY FK_6C38C0F8F92F3E70');
        // $this->addSql('ALTER TABLE dtb_customer_address DROP FOREIGN KEY FK_6C38C0F8E171EF5F');
        // $this->addSql('ALTER TABLE dtb_customer_favorite_product DROP FOREIGN KEY FK_ED6313839395C3F3');
        // $this->addSql('ALTER TABLE dtb_customer_favorite_product DROP FOREIGN KEY FK_ED6313834584665A');
        // $this->addSql('ALTER TABLE dtb_delivery DROP FOREIGN KEY FK_3420D9FA61220EA6');
        // $this->addSql('ALTER TABLE dtb_delivery DROP FOREIGN KEY FK_3420D9FAB0524E01');
        // $this->addSql('ALTER TABLE dtb_delivery_fee DROP FOREIGN KEY FK_491552412136921');
        // $this->addSql('ALTER TABLE dtb_delivery_fee DROP FOREIGN KEY FK_4915524E171EF5F');
        // $this->addSql('ALTER TABLE dtb_delivery_time DROP FOREIGN KEY FK_E80EE3A612136921');
        // $this->addSql('ALTER TABLE dtb_layout DROP FOREIGN KEY FK_5A62AA7C4FFA550E');
        // $this->addSql('ALTER TABLE dtb_login_history DROP FOREIGN KEY FK_6191DD4F9FA62FDD');
        // $this->addSql('ALTER TABLE dtb_login_history DROP FOREIGN KEY FK_6191DD4F7597D3FE');
        // $this->addSql('ALTER TABLE dtb_mail_history DROP FOREIGN KEY FK_4870AB118D9F6D38');
        // $this->addSql('ALTER TABLE dtb_mail_history DROP FOREIGN KEY FK_4870AB1161220EA6');
        // $this->addSql('ALTER TABLE dtb_mail_template DROP FOREIGN KEY FK_1CB16DB261220EA6');
        // $this->addSql('ALTER TABLE dtb_member DROP FOREIGN KEY FK_10BC3BE6BB3453DB');
        // $this->addSql('ALTER TABLE dtb_member DROP FOREIGN KEY FK_10BC3BE681EC865B');
        // $this->addSql('ALTER TABLE dtb_member DROP FOREIGN KEY FK_10BC3BE661220EA6');
        // $this->addSql('ALTER TABLE dtb_news DROP FOREIGN KEY FK_EA4C351761220EA6');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D8079395C3F3');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D807F92F3E70');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D807E171EF5F');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D8075A2DB2A0');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D807BE04EA9');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D8074C3A3BB');
        // $this->addSql('ALTER TABLE dtb_order DROP FOREIGN KEY FK_1D66D8074FFA550E');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3ED8D9F6D38');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3ED4584665A');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3ED21B06187');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3ED4887F3F8');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3ED1BD5C574');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3ED84042C99');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3EDA2505856');
        // $this->addSql('ALTER TABLE dtb_order_item DROP FOREIGN KEY FK_A0C8C3EDCAD13EAD');
        // $this->addSql('ALTER TABLE dtb_page DROP FOREIGN KEY FK_E3951A67D0618E8C');
        // $this->addSql('ALTER TABLE dtb_page_layout DROP FOREIGN KEY FK_F2799941C4663E4');
        // $this->addSql('ALTER TABLE dtb_page_layout DROP FOREIGN KEY FK_F27999418C22AA1A');
        // $this->addSql('ALTER TABLE dtb_payment DROP FOREIGN KEY FK_7AFF628F61220EA6');
        // $this->addSql('ALTER TABLE dtb_payment_option DROP FOREIGN KEY FK_5631540D12136921');
        // $this->addSql('ALTER TABLE dtb_payment_option DROP FOREIGN KEY FK_5631540D4C3A3BB');
        // $this->addSql('ALTER TABLE dtb_product DROP FOREIGN KEY FK_C49DE22F61220EA6');
        // $this->addSql('ALTER TABLE dtb_product DROP FOREIGN KEY FK_C49DE22F557B630');
        // $this->addSql('ALTER TABLE dtb_product_category DROP FOREIGN KEY FK_B05778914584665A');
        // $this->addSql('ALTER TABLE dtb_product_category DROP FOREIGN KEY FK_B057789112469DE2');
        // $this->addSql('ALTER TABLE dtb_product_class DROP FOREIGN KEY FK_1A11D1BA4584665A');
        // $this->addSql('ALTER TABLE dtb_product_class DROP FOREIGN KEY FK_1A11D1BAB0524E01');
        // $this->addSql('ALTER TABLE dtb_product_class DROP FOREIGN KEY FK_1A11D1BA248D128');
        // $this->addSql('ALTER TABLE dtb_product_class DROP FOREIGN KEY FK_1A11D1BA9B418092');
        // $this->addSql('ALTER TABLE dtb_product_class DROP FOREIGN KEY FK_1A11D1BABA4269E');
        // $this->addSql('ALTER TABLE dtb_product_class DROP FOREIGN KEY FK_1A11D1BA61220EA6');
        // $this->addSql('ALTER TABLE dtb_product_image DROP FOREIGN KEY FK_3267CC7A4584665A');
        // $this->addSql('ALTER TABLE dtb_product_image DROP FOREIGN KEY FK_3267CC7A61220EA6');
        // $this->addSql('ALTER TABLE dtb_product_stock DROP FOREIGN KEY FK_BC6C9E4521B06187');
        // $this->addSql('ALTER TABLE dtb_product_stock DROP FOREIGN KEY FK_BC6C9E4561220EA6');
        // $this->addSql('ALTER TABLE dtb_product_tag DROP FOREIGN KEY FK_4433E7214584665A');
        // $this->addSql('ALTER TABLE dtb_product_tag DROP FOREIGN KEY FK_4433E721BAD26311');
        // $this->addSql('ALTER TABLE dtb_product_tag DROP FOREIGN KEY FK_4433E72161220EA6');
        // $this->addSql('ALTER TABLE dtb_shipping DROP FOREIGN KEY FK_2EBD22CE8D9F6D38');
        // $this->addSql('ALTER TABLE dtb_shipping DROP FOREIGN KEY FK_2EBD22CEF92F3E70');
        // $this->addSql('ALTER TABLE dtb_shipping DROP FOREIGN KEY FK_2EBD22CEE171EF5F');
        // $this->addSql('ALTER TABLE dtb_shipping DROP FOREIGN KEY FK_2EBD22CE12136921');
        // $this->addSql('ALTER TABLE dtb_shipping DROP FOREIGN KEY FK_2EBD22CE61220EA6');
        // $this->addSql('ALTER TABLE dtb_tax_rule DROP FOREIGN KEY FK_59F696DE21B06187');
        // $this->addSql('ALTER TABLE dtb_tax_rule DROP FOREIGN KEY FK_59F696DE61220EA6');
        // $this->addSql('ALTER TABLE dtb_tax_rule DROP FOREIGN KEY FK_59F696DEF92F3E70');
        // $this->addSql('ALTER TABLE dtb_tax_rule DROP FOREIGN KEY FK_59F696DEE171EF5F');
        // $this->addSql('ALTER TABLE dtb_tax_rule DROP FOREIGN KEY FK_59F696DE4584665A');
        // $this->addSql('ALTER TABLE dtb_tax_rule DROP FOREIGN KEY FK_59F696DE1BD5C574');
        // $this->addSql('ALTER TABLE dtb_template DROP FOREIGN KEY FK_94C12A694FFA550E');
        // $this->addSql('DROP TABLE dtb_authority_role');
        // $this->addSql('DROP TABLE dtb_base_info');
        // $this->addSql('DROP TABLE dtb_block');
        // $this->addSql('DROP TABLE dtb_block_position');
        // $this->addSql('DROP TABLE dtb_calendar');
        // $this->addSql('DROP TABLE dtb_cart');
        // $this->addSql('DROP TABLE dtb_cart_item');
        // $this->addSql('DROP TABLE dtb_category');
        // $this->addSql('DROP TABLE dtb_class_category');
        // $this->addSql('DROP TABLE dtb_class_name');
        // $this->addSql('DROP TABLE dtb_csv');
        // $this->addSql('DROP TABLE dtb_customer');
        // $this->addSql('DROP TABLE dtb_customer_address');
        // $this->addSql('DROP TABLE dtb_customer_favorite_product');
        // $this->addSql('DROP TABLE dtb_delivery');
        // $this->addSql('DROP TABLE dtb_delivery_duration');
        // $this->addSql('DROP TABLE dtb_delivery_fee');
        // $this->addSql('DROP TABLE dtb_delivery_time');
        // $this->addSql('DROP TABLE dtb_layout');
        // $this->addSql('DROP TABLE dtb_login_history');
        // $this->addSql('DROP TABLE dtb_mail_history');
        // $this->addSql('DROP TABLE dtb_mail_template');
        // $this->addSql('DROP TABLE dtb_member');
        // $this->addSql('DROP TABLE dtb_news');
        // $this->addSql('DROP TABLE dtb_order');
        // $this->addSql('DROP TABLE dtb_order_item');
        // $this->addSql('DROP TABLE dtb_order_pdf');
        // $this->addSql('DROP TABLE dtb_page');
        // $this->addSql('DROP TABLE dtb_page_layout');
        // $this->addSql('DROP TABLE dtb_payment');
        // $this->addSql('DROP TABLE dtb_payment_option');
        // $this->addSql('DROP TABLE dtb_plugin');
        // $this->addSql('DROP TABLE dtb_product');
        // $this->addSql('DROP TABLE dtb_product_category');
        // $this->addSql('DROP TABLE dtb_product_class');
        // $this->addSql('DROP TABLE dtb_product_image');
        // $this->addSql('DROP TABLE dtb_product_stock');
        // $this->addSql('DROP TABLE dtb_product_tag');
        // $this->addSql('DROP TABLE dtb_shipping');
        // $this->addSql('DROP TABLE dtb_tag');
        // $this->addSql('DROP TABLE dtb_tax_rule');
        // $this->addSql('DROP TABLE dtb_template');
        // $this->addSql('DROP TABLE dtb_tradelaw');
        // $this->addSql('DROP TABLE mtb_authority');
        // $this->addSql('DROP TABLE mtb_country');
        // $this->addSql('DROP TABLE mtb_csv_type');
        // $this->addSql('DROP TABLE mtb_customer_order_status');
        // $this->addSql('DROP TABLE mtb_customer_status');
        // $this->addSql('DROP TABLE mtb_device_type');
        // $this->addSql('DROP TABLE mtb_job');
        // $this->addSql('DROP TABLE mtb_login_history_status');
        // $this->addSql('DROP TABLE mtb_order_item_type');
        // $this->addSql('DROP TABLE mtb_order_status');
        // $this->addSql('DROP TABLE mtb_order_status_color');
        // $this->addSql('DROP TABLE mtb_page_max');
        // $this->addSql('DROP TABLE mtb_pref');
        // $this->addSql('DROP TABLE mtb_product_list_max');
        // $this->addSql('DROP TABLE mtb_product_list_order_by');
        // $this->addSql('DROP TABLE mtb_product_status');
        // $this->addSql('DROP TABLE mtb_rounding_type');
        // $this->addSql('DROP TABLE mtb_sale_type');
        // $this->addSql('DROP TABLE mtb_sex');
        // $this->addSql('DROP TABLE mtb_tax_display_type');
        // $this->addSql('DROP TABLE mtb_tax_type');
        // $this->addSql('DROP TABLE mtb_work');
    }
}
